apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial-db
  template:
    metadata:
      labels:
        app: tutorial-db
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tutorial"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: tutorial-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-db
spec:
  selector:
    app: tutorial-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
